name: yatayat
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_pro_nullsafety: ^1.0.2
  cloud_firestore: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  nepali_date_picker: ^5.2.0
  nepali_utils: ^3.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.6
  pdf: ^3.6.1
  rename: ^2.0.1
  syncfusion_flutter_pdf: ^19.3.48-beta

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
